/**
 * This class is generated by jOOQ
 */
package com.github.adam6806.mediarequest.jooqgenerator.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class User extends org.jooq.impl.TableImpl<com.github.adam6806.mediarequest.jooqgenerator.tables.records.UserRecord> {

	private static final long serialVersionUID = -321562204;

	/**
	 * The reference instance of <code>request.user</code>
	 */
	public static final com.github.adam6806.mediarequest.jooqgenerator.tables.User USER = new com.github.adam6806.mediarequest.jooqgenerator.tables.User();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.github.adam6806.mediarequest.jooqgenerator.tables.records.UserRecord> getRecordType() {
		return com.github.adam6806.mediarequest.jooqgenerator.tables.records.UserRecord.class;
	}

	/**
	 * The column <code>request.user.email</code>.
	 */
	public final org.jooq.TableField<com.github.adam6806.mediarequest.jooqgenerator.tables.records.UserRecord, java.lang.String> EMAIL = createField("email", org.jooq.impl.SQLDataType.VARCHAR.length(256).nullable(false), this, "");

	/**
	 * The column <code>request.user.firstName</code>.
	 */
	public final org.jooq.TableField<com.github.adam6806.mediarequest.jooqgenerator.tables.records.UserRecord, java.lang.String> FIRSTNAME = createField("firstName", org.jooq.impl.SQLDataType.VARCHAR.length(256), this, "");

	/**
	 * The column <code>request.user.lastName</code>.
	 */
	public final org.jooq.TableField<com.github.adam6806.mediarequest.jooqgenerator.tables.records.UserRecord, java.lang.String> LASTNAME = createField("lastName", org.jooq.impl.SQLDataType.VARCHAR.length(256), this, "");

	/**
	 * The column <code>request.user.type</code>.
	 */
	public final org.jooq.TableField<com.github.adam6806.mediarequest.jooqgenerator.tables.records.UserRecord, java.lang.String> TYPE = createField("type", org.jooq.impl.SQLDataType.VARCHAR.length(256), this, "");

	/**
	 * The column <code>request.user.joinDate</code>.
	 */
	public final org.jooq.TableField<com.github.adam6806.mediarequest.jooqgenerator.tables.records.UserRecord, java.sql.Date> JOINDATE = createField("joinDate", org.jooq.impl.SQLDataType.DATE, this, "");

	/**
	 * The column <code>request.user.lastLogin</code>.
	 */
	public final org.jooq.TableField<com.github.adam6806.mediarequest.jooqgenerator.tables.records.UserRecord, java.sql.Date> LASTLOGIN = createField("lastLogin", org.jooq.impl.SQLDataType.DATE, this, "");

	/**
	 * The column <code>request.user.numberOfRequests</code>.
	 */
	public final org.jooq.TableField<com.github.adam6806.mediarequest.jooqgenerator.tables.records.UserRecord, java.lang.Integer> NUMBEROFREQUESTS = createField("numberOfRequests", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * Create a <code>request.user</code> table reference
	 */
	public User() {
		this("user", null);
	}

	/**
	 * Create an aliased <code>request.user</code> table reference
	 */
	public User(java.lang.String alias) {
		this(alias, com.github.adam6806.mediarequest.jooqgenerator.tables.User.USER);
	}

	private User(java.lang.String alias, org.jooq.Table<com.github.adam6806.mediarequest.jooqgenerator.tables.records.UserRecord> aliased) {
		this(alias, aliased, null);
	}

	private User(java.lang.String alias, org.jooq.Table<com.github.adam6806.mediarequest.jooqgenerator.tables.records.UserRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.github.adam6806.mediarequest.jooqgenerator.Request.REQUEST, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.github.adam6806.mediarequest.jooqgenerator.tables.records.UserRecord> getPrimaryKey() {
		return com.github.adam6806.mediarequest.jooqgenerator.Keys.USERKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.github.adam6806.mediarequest.jooqgenerator.tables.records.UserRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.github.adam6806.mediarequest.jooqgenerator.tables.records.UserRecord>>asList(com.github.adam6806.mediarequest.jooqgenerator.Keys.USERKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.github.adam6806.mediarequest.jooqgenerator.tables.User as(java.lang.String alias) {
		return new com.github.adam6806.mediarequest.jooqgenerator.tables.User(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.github.adam6806.mediarequest.jooqgenerator.tables.User rename(java.lang.String name) {
		return new com.github.adam6806.mediarequest.jooqgenerator.tables.User(name, null);
	}
}
