/**
 * This class is generated by jOOQ
 */
package com.github.adam6806.mediarequest.jooqgenerator.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RequestRecord extends org.jooq.impl.UpdatableRecordImpl<com.github.adam6806.mediarequest.jooqgenerator.tables.records.RequestRecord> implements org.jooq.Record6<java.lang.String, java.lang.String, java.lang.Boolean, java.lang.String, java.lang.String, java.lang.String> {

	private static final long serialVersionUID = -1946746850;

	/**
	 * Setter for <code>request.request.email</code>.
	 */
	public void setEmail(java.lang.String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>request.request.email</code>.
	 */
	public java.lang.String getEmail() {
		return (java.lang.String) getValue(0);
	}

	/**
	 * Setter for <code>request.request.mediaId</code>.
	 */
	public void setMediaid(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>request.request.mediaId</code>.
	 */
	public java.lang.String getMediaid() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>request.request.isMovie</code>.
	 */
	public void setIsmovie(java.lang.Boolean value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>request.request.isMovie</code>.
	 */
	public java.lang.Boolean getIsmovie() {
		return (java.lang.Boolean) getValue(2);
	}

	/**
	 * Setter for <code>request.request.posterImageUrl</code>.
	 */
	public void setPosterimageurl(java.lang.String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>request.request.posterImageUrl</code>.
	 */
	public java.lang.String getPosterimageurl() {
		return (java.lang.String) getValue(3);
	}

	/**
	 * Setter for <code>request.request.description</code>.
	 */
	public void setDescription(java.lang.String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>request.request.description</code>.
	 */
	public java.lang.String getDescription() {
		return (java.lang.String) getValue(4);
	}

	/**
	 * Setter for <code>request.request.requestDate</code>.
	 */
	public void setRequestdate(java.lang.String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>request.request.requestDate</code>.
	 */
	public java.lang.String getRequestdate() {
		return (java.lang.String) getValue(5);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.String> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record6 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row6<java.lang.String, java.lang.String, java.lang.Boolean, java.lang.String, java.lang.String, java.lang.String> fieldsRow() {
		return (org.jooq.Row6) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row6<java.lang.String, java.lang.String, java.lang.Boolean, java.lang.String, java.lang.String, java.lang.String> valuesRow() {
		return (org.jooq.Row6) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field1() {
		return com.github.adam6806.mediarequest.jooqgenerator.tables.Request.REQUEST.EMAIL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return com.github.adam6806.mediarequest.jooqgenerator.tables.Request.REQUEST.MEDIAID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Boolean> field3() {
		return com.github.adam6806.mediarequest.jooqgenerator.tables.Request.REQUEST.ISMOVIE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field4() {
		return com.github.adam6806.mediarequest.jooqgenerator.tables.Request.REQUEST.POSTERIMAGEURL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field5() {
		return com.github.adam6806.mediarequest.jooqgenerator.tables.Request.REQUEST.DESCRIPTION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field6() {
		return com.github.adam6806.mediarequest.jooqgenerator.tables.Request.REQUEST.REQUESTDATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value1() {
		return getEmail();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getMediaid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Boolean value3() {
		return getIsmovie();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value4() {
		return getPosterimageurl();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value5() {
		return getDescription();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value6() {
		return getRequestdate();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RequestRecord value1(java.lang.String value) {
		setEmail(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RequestRecord value2(java.lang.String value) {
		setMediaid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RequestRecord value3(java.lang.Boolean value) {
		setIsmovie(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RequestRecord value4(java.lang.String value) {
		setPosterimageurl(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RequestRecord value5(java.lang.String value) {
		setDescription(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RequestRecord value6(java.lang.String value) {
		setRequestdate(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RequestRecord values(java.lang.String value1, java.lang.String value2, java.lang.Boolean value3, java.lang.String value4, java.lang.String value5, java.lang.String value6) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached RequestRecord
	 */
	public RequestRecord() {
		super(com.github.adam6806.mediarequest.jooqgenerator.tables.Request.REQUEST);
	}

	/**
	 * Create a detached, initialised RequestRecord
	 */
	public RequestRecord(java.lang.String email, java.lang.String mediaid, java.lang.Boolean ismovie, java.lang.String posterimageurl, java.lang.String description, java.lang.String requestdate) {
		super(com.github.adam6806.mediarequest.jooqgenerator.tables.Request.REQUEST);

		setValue(0, email);
		setValue(1, mediaid);
		setValue(2, ismovie);
		setValue(3, posterimageurl);
		setValue(4, description);
		setValue(5, requestdate);
	}
}
