/**
 * This class is generated by jOOQ
 */
package com.github.adam6806.mediarequest.jooqgenerator;

/**
 * A class modelling foreign key relationships between tables of the <code>request</code> 
 * schema
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

	// -------------------------------------------------------------------------
	// IDENTITY definitions
	// -------------------------------------------------------------------------


	// -------------------------------------------------------------------------
	// UNIQUE and PRIMARY KEY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.UniqueKey<com.github.adam6806.mediarequest.jooqgenerator.tables.records.RequestRecord> KEY = UniqueKeys0.KEY;
	public static final org.jooq.UniqueKey<com.github.adam6806.mediarequest.jooqgenerator.tables.records.UserRecord> USERKEY = UniqueKeys0.USERKEY;

	// -------------------------------------------------------------------------
	// FOREIGN KEY definitions
	// -------------------------------------------------------------------------


	// -------------------------------------------------------------------------
	// [#1459] distribute members to avoid static initialisers > 64kb
	// -------------------------------------------------------------------------

	private static class UniqueKeys0 extends org.jooq.impl.AbstractKeys {
		public static final org.jooq.UniqueKey<com.github.adam6806.mediarequest.jooqgenerator.tables.records.RequestRecord> KEY = createUniqueKey(com.github.adam6806.mediarequest.jooqgenerator.tables.Request.REQUEST, com.github.adam6806.mediarequest.jooqgenerator.tables.Request.REQUEST.MEDIAID);
		public static final org.jooq.UniqueKey<com.github.adam6806.mediarequest.jooqgenerator.tables.records.UserRecord> USERKEY = createUniqueKey(com.github.adam6806.mediarequest.jooqgenerator.tables.User.USER, com.github.adam6806.mediarequest.jooqgenerator.tables.User.USER.EMAIL);
	}
}
