/**
 * This class is generated by jOOQ
 */
package com.github.adam6806.mediarequest.jooqgenerator;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Request extends org.jooq.impl.SchemaImpl {

	private static final long serialVersionUID = 197060078;

	/**
	 * The reference instance of <code>request</code>
	 */
	public static final Request REQUEST = new Request();

	/**
	 * No further instances allowed
	 */
	private Request() {
		super("request");
	}

	@Override
	public final java.util.List<org.jooq.Table<?>> getTables() {
		java.util.List result = new java.util.ArrayList();
		result.addAll(getTables0());
		return result;
	}

	private final java.util.List<org.jooq.Table<?>> getTables0() {
		return java.util.Arrays.<org.jooq.Table<?>>asList(
			com.github.adam6806.mediarequest.jooqgenerator.tables.Request.REQUEST,
			com.github.adam6806.mediarequest.jooqgenerator.tables.User.USER);
	}
}
