/**
 * This class is generated by jOOQ
 */
package com.github.adam6806.mediarequest.jooqgenerator;

/**
 * Convenience access to all tables in request
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table request.request
	 */
	public static final com.github.adam6806.mediarequest.jooqgenerator.tables.Request REQUEST = com.github.adam6806.mediarequest.jooqgenerator.tables.Request.REQUEST;

	/**
	 * The table request.user
	 */
	public static final com.github.adam6806.mediarequest.jooqgenerator.tables.User USER = com.github.adam6806.mediarequest.jooqgenerator.tables.User.USER;
}
